BoxLayout:
    orientation: 'vertical'
    AppBar:
    Widget:

<AppBar@BoxLayout>:
    canvas:
        Color:
            rgba:0.0.3 ,0.13.1
        Rectangle:
            size: self.size
            pos:self.pos
        size_hint_y:None
        height:'50dp'
        Label:
            text: 'MuriloWhats'
            bold: True
            font_size: '20dp'
            haling: 'left'
            text_size:self.size
            valign:'center'
            padding_x:'10dp'